#!/bin/bash
FULLPATH=`cd $(dirname $0); pwd`
PROJECT=`echo $FULLPATH | awk -F/ '{print $(NF-2)}'`
STATUS=`echo $0 | awk -F- '{print $NF == "worked" ? "pass" : "fail"}'`
PW=`cat $(dirname $0)/../../../credentials`
curl -u $PW -d"" -- http://ci.edendevelopment.co.uk/dashboard/build/$PROJECT/$STATUS
echo
